insert into Products (product_id, name, isseafood) values (1, 'Falafel', 0);
insert into Products (product_id, name, isseafood) values (2, 'Pork', 0);
insert into Products (product_id, name, isseafood) values (3, 'Cauliflower and pineapple curry', 0);
insert into Products (product_id, name, isseafood) values (4, 'Duck and chili powder salad', 0);
insert into Products (product_id, name, isseafood) values (5, 'Clementine and tofu salad', 0);
insert into Products (product_id, name, isseafood) values (6, 'Shrimps', 1);
insert into Products (product_id, name, isseafood) values (7, 'Chocolate and caramel mousse', 0);
insert into Products (product_id, name, isseafood) values (8, 'Yoghurt and marzipan cake', 0);
insert into Products (product_id, name, isseafood) values (9, 'Lobster', 1);
insert into Products (product_id, name, isseafood) values (10, 'Pesto and sausage parcels', 0);
insert into Products (product_id, name, isseafood) values (11, 'Crab and egg vindaloo', 1);
insert into Products (product_id, name, isseafood) values (12, 'Almond and pumpkin seed buns', 0);
insert into Products (product_id, name, isseafood) values (13, 'Rice and sweet mincemeat pie', 0);
insert into Products (product_id, name, isseafood) values (14, 'Breadfruit and dragon fruit salad', 0);
insert into Products (product_id, name, isseafood) values (15, 'Zabaglione and tempeh salad', 0);
insert into Products (product_id, name, isseafood) values (16, 'Duck and chili powder salad', 0);
insert into Products (product_id, name, isseafood) values (17, 'Peanut and mushroom stew', 0);
insert into Products (product_id, name, isseafood) values (18, 'Chickpea and duck madras', 0);
insert into Products (product_id, name, isseafood) values (19, 'Avocado and salmon sushi', 1);
insert into Products (product_id, name, isseafood) values (20, 'Fish soup', 1);
